kind: pipeline
type: kubernetes

name: default-pipeline

steps:
- name: build-image
  image: plugins/ecr
  settings:
    repo: mapa-da-violencia
    registry: 716814888065.dkr.ecr.us-east-2.amazonaws.com
    region: us-east-2
    dockerfile: Dockerfile
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}

tolerations:
- dedicated: jenkinsAgents
  operator: Exists
  effect: NoSchedule

trigger:
  event:
  - push
  branch:
  - main

